### PR TITLE
Improved toc for Monash theme

### PR DESCRIPTION
**Pull request by robjhyndman**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Looks good to me.  Shall we update the example use and show it there?

**Comment by robjhyndman** [comment]
Sure. That would be good.

**Comment by eddelbuettel** [comment]
Can you suggest the one or two use case and maybe fold them into then standard template / use case given that we do not have a separate one for Monash?

**Comment by robjhyndman** [comment]
I've added a Monash demo as I thought that would be more transparent.

**Comment by eddelbuettel** [comment]
Fabulous.

**Pull request merged**
