### PR TITLE
Improvements to Monash template

### PR DESCRIPTION
**Pull request by robjhyndman**
* Allowed user-specified title page
* Fall back to bera font if carlito not available.

As per https://github.com/eddelbuettel/binb/issues/12

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Nice!  Do you have a (test or illustration) example for the titlepage mod?

**Comment by robjhyndman** [comment]
Yes. Where should it go?

**Comment by eddelbuettel** [comment]
Maybe `inst/monashDemo/userTitleDemo.{Rmd,pdf}` ?

**Comment by robjhyndman** [comment]
Done. I showed off a couple of other options as well.

**Comment by eddelbuettel** [comment]
Love it.  Will merge and peruse.  Thanks much!

**Pull request merged**
