### PR TITLE
Enable beamer options via yaml metadata

### PR DESCRIPTION
**Pull request by jolars**
This small pull request adds the ability to pass options for beamer along through the metadata argument `beameroption` for the monash, iqss, and metropolis themes. In addition, it adds the `pgfpages` package to these templates' themes so that some options, such as "show notes on second screen", work without having to manually require the package.

The edits come straight from the official pandoc template for latex:

<https://github.com/jgm/pandoc-templates/blob/64a929d7eec7f2c0b741433b30d6b904354a4e74/default.latex#L42-L49>

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Hi @jolars that looks pretty nice and clean.   Two questions, though:

1) Do you have an example use we could (should) stick into the demos?   

2) How common in `pgfpages`?  Should the latex code test for ir being available?  Ie. my Ubuntu machines seem to have it in `texlive-pictures`, I can imagine some more "narrow" machines not having all of texlive installed.  We probably would not want them to break.  A quick googleing lead me to https://tex.stackexchange.com/questions/15306/conditional-if-a-package-is-available -- shall we add logic like it?

**Comment by jolars** [comment]
1. I took the liberty to modify the metropolis demo (vignette) by adding a slide using notes. Would something like that work?
2. You're right. I added the `IfFileExists` command to check for existence of `pgfpages.sty`.

**Comment by eddelbuettel** [comment]
@izahn @robjhyndman Any comments or objections?  Looks like a nice and clean addition.

**Comment by izahn** [comment]
Looks good to me :+1:

**Comment by robjhyndman** [comment]
Me too. A nice addition.

**Comment by eddelbuettel** [comment]
Yes indeed -- nice work and thank @jolars 

I'll do some follow-up polish like the missing ChangeLog etc. Probably tomorrow.

**Pull request merged**
